{
 "title": "Speed Test Dashboard",
 "time": { "from": "now-10d", "to": "now" },
 "panels": [
  {
   "title": "Date Time",
   "type": "grafana-clock-panel",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  created AS \"time\",\n  lat\nFROM speedtester_serversmodel\nWHERE\n  $__timeFilter(created)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Min/Max Download Speed",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  min(download) AS \"min down\",\n  max(download) AS \"max down\"\nFROM speedtester_speedtestermodel"
    }
   ]
  },
  {
   "title": "Min/Max Upload Speed",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  min(upload) AS \"min upload\",\n  max(upload) AS \"max upload\"\nFROM speedtester_speedtestermodel"
    }
   ]
  },
  {
   "title": "Last Speed Test D/U",
   "type": "stat",
   "gridPos": { "h": 8, "w": 15, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  created AS \"time\",\n  download\nFROM speedtester_speedtestermodel\nWHERE\n  $__timeFilter(created)\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  created AS \"time\",\n  upload\nFROM speedtester_speedtestermodel\nWHERE\n  $__timeFilter(created)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "AVG D/U Speed",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 3, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  avg(download) AS \"avg download\",\n  avg(upload) AS \"avg upload\"\nFROM speedtester_speedtestermodel"
    }
   ]
  },
  {
   "title": "Speed Test Series",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 9, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n  created AS \"time\",\n  download\nFROM speedtester_speedtestermodel\nWHERE\n  $__timeFilter(created)\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  created AS \"time\",\n  upload\nFROM speedtester_speedtestermodel\nWHERE\n  $__timeFilter(created)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Pinged Servers",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 16, "w": 15, "x": 9, "y": 8 },
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  lat, lon,d, name\nFROM speedtester_serversmodel\nWHERE\n  $__timeFilter(created)\nORDER BY 1"
    }
   ]
  }
 ]
}