{
 "title": "Overview",
 "panels": [
  {
   "title": "Docker Containers",
   "description": "Containers metrics",
   "panels": [
    {
     "title": "CPU Load",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
     "format": "percent",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum(rate(container_cpu_user_seconds_total{image!=\"\"}[1m])) / count(node_cpu_seconds_total{mode=\"user\"}) * 100"
      }
     ]
    },
    {
     "title": "CPU Cores",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "machine_cpu_cores{instance=\"cadvisor:8080\", job=\"docker\"}\n"
      }
     ]
    },
    {
     "title": "Memory Load",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
     "format": "percent",
     "valueName": "avg",
     "targets": [
      {
       "expr": "(sum(node_memory_MemTotal_bytes) - sum(node_memory_MemFree_bytes+node_memory_Buffers_bytes+node_memory_Cached_bytes) ) / sum(node_memory_MemTotal_bytes) * 100"
      }
     ]
    },
    {
     "title": "Used Memory",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
     "format": "bytes",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum(container_memory_usage_bytes{image!=\"\"})"
      }
     ]
    },
    {
     "title": "Storage Load",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
     "format": "percent",
     "valueName": "avg",
     "targets": [
      {
       "expr": "(node_filesystem_size_bytes{fstype=\"aufs\"} - node_filesystem_free_bytes{fstype=\"aufs\"}) / node_filesystem_size_bytes{fstype=\"aufs\"}  * 100"
      }
     ]
    },
    {
     "title": "Used Storage",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
     "format": "bytes",
     "valueName": "avg",
     "targets": [
      { "expr": "sum(container_fs_usage_bytes)" }
     ]
    },
    {
     "title": "Running Containers",
     "type": "graph",
     "gridPos": { "h": 4, "w": 8, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "scalar(count(container_memory_usage_bytes{image!=\"\"}) > 0)",
       "legendFormat": "containers"
      }
     ]
    },
    {
     "title": "System Load",
     "type": "graph",
     "gridPos": { "h": 4, "w": 8, "x": 8, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "node_load1", "legendFormat": "load 1m" }
     ]
    },
    {
     "title": "I/O Usage",
     "type": "graph",
     "gridPos": { "h": 4, "w": 8, "x": 16, "y": 4 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(irate(node_disk_read_bytes_total[5m]))",
       "legendFormat": "read"
      },
      {
       "expr": "sum(irate(node_disk_written_bytes_total[5m]))",
       "legendFormat": "written"
      },
      {
       "expr": "sum(irate(node_disk_io_time_seconds_total[5m]))",
       "legendFormat": "io time"
      }
     ]
    },
    {
     "title": "Container CPU Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "sum by (name) (rate(container_cpu_usage_seconds_total{image!=\"\"}[1m])) / scalar(count(node_cpu_seconds_total{mode=\"user\"})) * 100",
       "legendFormat": "{{ name }}"
      }
     ]
    },
    {
     "title": "Container Memory Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum by (name)(container_memory_usage_bytes{image!=\"\"})",
       "legendFormat": "{{ name }}"
      }
     ]
    },
    {
     "title": "Container Cached Memory Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum by (name) (container_memory_cache{image!=\"\"})",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Container Network Input",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum by (name) (rate(container_network_receive_bytes_total{image!=\"\"}[1m]))",
       "legendFormat": "{{ name }}"
      }
     ]
    },
    {
     "title": "Container Network Output",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 36 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum by (name) (rate(container_network_transmit_bytes_total{image!=\"\"}[1m]))",
       "legendFormat": "{{ name }}"
      }
     ]
    }
   ]
  },
  {
   "title": "CPU Load",
   "type": "singlestat",
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(container_cpu_user_seconds_total{image!=\"\"}[1m])) / count(node_cpu_seconds_total{mode=\"user\"}) * 100"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "singlestat",
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "machine_cpu_cores" }
   ]
  },
  {
   "title": "Memory Load",
   "type": "singlestat",
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "(sum(node_memory_MemTotal_bytes) - sum(node_memory_MemFree_bytes+node_memory_Buffers_bytes+node_memory_Cached_bytes) ) / sum(node_memory_MemTotal_bytes) * 100"
    }
   ]
  },
  {
   "title": "Used Memory",
   "type": "singlestat",
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{image!=\"\"})"
    }
   ]
  },
  {
   "title": "Storage Load",
   "type": "singlestat",
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "(node_filesystem_size_bytes{fstype=\"aufs\"} - node_filesystem_free_bytes{fstype=\"aufs\"}) / node_filesystem_size_bytes{fstype=\"aufs\"}  * 100"
    }
   ]
  },
  {
   "title": "Used Storage",
   "type": "singlestat",
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    { "expr": "sum(container_fs_usage_bytes)" }
   ]
  }
 ]
}
{
 "title": "Host stats",
 "panels": [
  {
   "title": "Running Containers",
   "type": "graph",
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "scalar(count(container_memory_usage_bytes{image!=\"\"}) > 0)",
     "legendFormat": "containers"
    }
   ]
  },
  {
   "title": "System Load",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "node_load1", "legendFormat": "load 1m" }
   ]
  },
  {
   "title": "I/O Usage",
   "type": "graph",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(irate(node_disk_read_bytes_total[5m]))",
     "legendFormat": "read"
    },
    {
     "expr": "sum(irate(node_disk_written_bytes_total[5m]))",
     "legendFormat": "written"
    },
    {
     "expr": "sum(irate(node_disk_io_time_seconds_total[5m]))",
     "legendFormat": "io time"
    }
   ]
  }
 ]
}
{
 "title": "CPU",
 "panels": [
  {
   "title": "Container CPU Usage",
   "type": "graph",
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum by (name) (rate(container_cpu_usage_seconds_total{image!=\"\"}[1m])) / scalar(count(node_cpu_seconds_total{mode=\"user\"})) * 100",
     "legendFormat": "{{ name }}"
    }
   ]
  }
 ]
}
{
 "title": "Memory",
 "panels": [
  {
   "title": "Container Memory Usage",
   "type": "graph",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (name)(container_memory_usage_bytes{image!=\"\"})",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Container Cached Memory Usage",
   "type": "graph",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (name) (container_memory_cache{image!=\"\"})",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}
{
 "title": "Network",
 "panels": [
  {
   "title": "Container Network Input",
   "type": "graph",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (name) (rate(container_network_receive_bytes_total{image!=\"\"}[1m]))",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Container Network Output",
   "type": "graph",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (name) (rate(container_network_transmit_bytes_total{image!=\"\"}[1m]))",
     "legendFormat": "{{ name }}"
    }
   ]
  }
 ]
}