# Generated by Django 3.2 on 2022-05-31 10:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServersModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('url', models.URLField(verbose_name='url')),
                ('lat', models.FloatField(verbose_name='lat')),
                ('lon', models.FloatField(verbose_name='lon')),
                ('name', models.CharField(max_length=256, verbose_name='city')),
                ('country', models.CharField(max_length=256, verbose_name='country')),
                ('cc', models.CharField(max_length=5, verbose_name='country code')),
                ('sponsor', models.CharField(max_length=256, verbose_name='sponsor')),
                ('host', models.CharField(max_length=256, verbose_name='host')),
                ('d', models.FloatField(verbose_name='d')),
                ('latency', models.FloatField(verbose_name='latency')),
            ],
            options={
                'verbose_name': 'Server',
                'verbose_name_plural': 'Servers',
            },
        ),
        migrations.CreateModel(
            name='SpeedtesterModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('download', models.FloatField(verbose_name='download')),
                ('upload', models.FloatField(verbose_name='upload')),
                ('lat', models.FloatField(verbose_name='lat')),
                ('lon', models.FloatField(verbose_name='lon')),
                ('best_server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='speedtester.serversmodel')),
            ],
            options={
                'verbose_name': 'Speed Test',
                'verbose_name_plural': 'Speed Tests',
            },
        ),
    ]
