# docker image action.yml
name: 'Docker Build and Push'
description: 'Build, push docker images to container registry'
inputs:
  username:
    description: 'username for registry'
    required: true
    default: 'none'
  password:
    description: 'password for registry'
    required: true
    default: 'none'
  registry: # id of input
    description: 'Registry name (ex. ghcr.io, registry.gitlab.com)'
    required: true
    default: 'ghcr.io'
  repository:
    description: 'repository name '
    required: true
    default: 'test'
  tag: # id of input
    description: 'Custom tag for docker image'
    required: false
    default: 'latest'
  file:
    description: 'Path for dockerfile'
    required: true
    default: 'Dockerfile'

runs:
  using: "composite"
  steps:
    - run: echo "${{ inputs.registry }} ${{ inputs.registry }} "
      shell: bash
#    - run: docker login ${{ inputs.registry }} -u ${{ inputs.registry }} -p ${{ inputs.password }}
#      shell: bash
#    - run: docker build . --file ${{ inputs.file }} --tag ${{ inputs.registry }}/${{ input.repository }}:${{ input.tag }}
#      shell: bash
#    - run: docker push ${{ inputs.registry }}/${{ input.repository }}:${{ input.tag }}
#      shell: bash