# # config file version
# https://gist.github.com/wwerner/803a9569e3048fe8372d08f596c6da82
apiVersion: 1

# # list of datasources to insert/update depending
# # on what's available in the database
datasources:
  # <string, required> name of the datasource. Required
  - name: PostgreSQL
    # <string, required> datasource type. Required
    type: postgres
    # <string, required> access mode. direct or proxy. Required
    access: direct
    # <string> url
    url: postgres:5432
    # <string> database password, if used
    secureJsonData:
      password: "Password!"
    # <string> database user, if used
    user: refresher
    # <string> database name, if used
    database: refresher
    editable: true
    version: 10
    jsonData:
      sslmode: "disable" # disable/require/verify-ca/verify-full
      connMaxLifetime: 14400  # Grafana v5.4+
      postgresVersion: 903 # 903=9.3, 904=9.4, 905=9.5, 906=9.6, 1000=10
      timescaledb: false
      tlsAuth: false
      tlsAuthWithCACert: false

#  - name: Prometheus
#    type: prometheus
#    access: proxy
#    orgId: 1
#    url: http://prometheus:9090
#    basicAuth: false
#    isDefault: true
#    editable: true