# # config file version
# https://gist.github.com/wwerner/803a9569e3048fe8372d08f596c6da82
apiVersion: 1


# # list of datasources to insert/update depending
# # on what's available in the database
datasources:
   # <string, required> name of the datasource. Required
 - name: PostgreSQL
   # <string, required> datasource type. Required
   type: postgres
   # <string, required> access mode. direct or proxy. Required
   access: direct
   # <string> url
   url: postgres:5432
   # <string> database password, if used
   secureJsonData:
      password: "Password!"
   # <string> database user, if used
   user: refresher
   # <string> database name, if used
   database: refresher
   editable: true
   jsonData:
     sslmode: "disable" # disable/require/verify-ca/verify-full
     connMaxLifetime: 14400  # Grafana v5.4+
     postgresVersion: 903 # 903=9.3, 904=9.4, 905=9.5, 906=9.6, 1000=10
     timescaledb: false
     tlsAuth: false
     tlsAuthWithCACert: false
   #      httpHeaderName1: "Authorization"
   # <bool> enable/disable basic auth
#   basicAuth: false
#   # <string> basic auth username
#   basicAuthUser:
#   # <string> basic auth password
#   basicAuthPassword:
#   # <bool> enable/disable with credentials headers
#   withCredentials:
#   # <bool> mark as default datasource. Max one per org
#   isDefault:
#   # <map> fields that will be converted to json and stored in json_data
#   # <string> json object of data that will be encrypted.
#   secureJsonData:
#     tlsCACert: "..."
#     tlsClientCert: "..."
#     tlsClientKey: "..."
#     # <openshift\kubernetes token example>
#     httpHeaderValue1: "Bearer xf5yhfkpsnmgo"
#   # <bool> allow users to edit datasources from the UI.
