name: Docker Image CI

on:
  push:
    branches: [ REF-5-circle-ci ]
  pull_request:
    branches: [ REF-5-circle-ci ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file docker/Dockerfile --tag my-image-name:$(date +%s)
